# Python program to demonstrate basic operations on single array and multiple arrays

## 1. Creating Single and Multi-dimensional Arrays:

In [58]:
import numpy as np

In [60]:
# Single-dimensional array
single_array = np.array([1, 2, 3, 4, 5])

In [62]:
# Multi-dimensional array (2D array with 3 rows and 4 columns)
multi_array = np.array([[1, 2, 3, 4], 
                        [5, 6, 7, 8], 
                        [9, 10, 11, 12]])

In [64]:
# Printing the arrays
print("Single-dimensional array:")
print(single_array)

print("\nMulti-dimensional array:")
print(multi_array)

Single-dimensional array:
[1 2 3 4 5]

Multi-dimensional array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Accessing and Modifying Elements in a Multi-dimensional Array:

In [69]:
# Accessing an element at row 1, column 2
element = multi_array[1, 2]
print("\nElement at row 1, column 2:", element)  # Output: 7


Element at row 1, column 2: 7


In [71]:
# Modifying an element at row 0, column 3
multi_array[0, 3] = 20

# Printing the modified array
print("\nModified Multi-dimensional array:")
print(multi_array)


Modified Multi-dimensional array:
[[ 1  2  3 20]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 3. Performing Operations on a Multi-dimensional Array:

In [74]:
# Calculating the sum of all elements in the multi-dimensional array
total_sum = np.sum(multi_array)
print("\nSum of all elements in the multi-dimensional array:", total_sum)  # Output: 78


Sum of all elements in the multi-dimensional array: 94


In [76]:
# Calculating the mean of each row
mean_of_rows = np.mean(multi_array, axis=1)
print("\nMean of each row:", mean_of_rows)  # Output: [ 2.5  6.5 10.5]


Mean of each row: [ 6.5  6.5 10.5]


In [78]:
# Creating another multi-dimensional array for dot product
b = np.array([[2, 3], 
              [4, 5], 
              [6, 7], 
              [8, 9]])

# Calculating the dot product of the two matrices
dot_product = np.dot(multi_array, b)
print("\nDot product of the arrays:")
print(dot_product)


Dot product of the arrays:
[[188 214]
 [140 166]
 [220 262]]
